export const APP_CONSTANTS = {
  MESSAGE_MAX_LENGTH: 4000,
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 32,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  CONVERSATION_NAME_MAX_LENGTH: 80,
  CONVERSATION_TOPIC_MAX_LENGTH: 250,
  MAX_UPLOAD_SIZE_BYTES: 25 * 1024 * 1024, // 25 MB
  TYPING_THROTTLE_MS: 2000,
  TYPING_TIMEOUT_MS: 5000,
  PRESENCE_HEARTBEAT_INTERVAL_MS: 25000,
  PRESENCE_TTL_SECONDS: 60,
  DEFAULT_PAGE_SIZE: 50,
  MAX_PAGE_SIZE: 100,
} as const;

export const ALLOWED_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
  'application/pdf',
  'text/plain',
  'text/markdown',
  'application/zip',
] as const;

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
} as const;
